# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [3]:
x = boston.data
y = boston.target

In [4]:
x.shape, y.shape

((506, 13), (506,))

In [5]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test =\
        train_test_split(x, y, random_state=2022, test_size=0.2)

In [9]:
x_train.shape, y_train.shape

((404, 13), (404,))

In [10]:
########
# 모델링 : Sequential API
########

# 1번 세션 클리어
keras.backend.clear_session()

# 2번 모델 선언 : 레이어 블록을 조립할 발판 생성
model = keras.models.Sequential()

# 3번 레이어 블록 조립 : .add()
model.add( keras.layers.Input(shape=(13,)) )
model.add( keras.layers.Dense(1) )

# 4번 컴파일
model.compile(loss='mse', optimizer=keras.optimizers.Adam(learning_rate=0.01) )

# 양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [11]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
13/13 [==============================] - 0s 583us/step - loss: 31945.3887
Epoch 2/10
13/13 [==============================] - 0s 500us/step - loss: 9402.9277
Epoch 3/10
13/13 [==============================] - 0s 500us/step - loss: 5665.4580
Epoch 4/10
13/13 [==============================] - 0s 500us/step - loss: 4901.1270
Epoch 5/10
13/13 [==============================] - 0s 583us/step - loss: 3754.3335
Epoch 6/10
13/13 [==============================] - 0s 584us/step - loss: 2859.7905
Epoch 7/10
13/13 [==============================] - 0s 500us/step - loss: 2254.5581
Epoch 8/10
13/13 [==============================] - 0s 583us/step - loss: 1738.2661
Epoch 9/10
13/13 [==============================] - 0s 500us/step - loss: 1368.9333
Epoch 10/10
13/13 [==============================] - 0s 417us/step - loss: 1079.3507


In [13]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

In [14]:
y_pred[:5].reshape(-1)

array([22.934908 , 23.643503 ,  7.2012143, 17.286657 , 36.241936 ],
      dtype=float32)

In [16]:
y_test[:5].reshape(-1)

array([20.1, 11.9, 20.6, 33.2, 20.8])

# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [17]:
x_train.shape, y_train.shape

((404, 13), (404,))

In [18]:
########
# 모델링 : Sequential API
########

# 1번 세션 클리어
keras.backend.clear_session()

# 2번 모델 발판 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(13,), name='input_layer') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(1, name='output_layer'))

# 4번 컴파일
model.compile(loss='mse', optimizer=keras.optimizers.Adam(learning_rate=0.01))

# 양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 output_layer (Dense)        (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


In [19]:
###########
# 모델 학습
###########

model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
13/13 [==============================] - 0s 667us/step - loss: 1575.4532
Epoch 2/10
13/13 [==============================] - 0s 584us/step - loss: 185.1937
Epoch 3/10
13/13 [==============================] - 0s 583us/step - loss: 71.9873
Epoch 4/10
13/13 [==============================] - 0s 618us/step - loss: 67.8257
Epoch 5/10
13/13 [==============================] - 0s 584us/step - loss: 64.3515
Epoch 6/10
13/13 [==============================] - 0s 500us/step - loss: 64.0996
Epoch 7/10
13/13 [==============================] - 0s 583us/step - loss: 60.6719
Epoch 8/10
13/13 [==============================] - 0s 583us/step - loss: 59.4374
Epoch 9/10
13/13 [==============================] - 0s 583us/step - loss: 60.6191
Epoch 10/10
13/13 [==============================] - 0s 583us/step - loss: 57.8535


In [21]:
###########
# 모델 예측
###########

y_pred = model.predict(x_test)

y_pred[:5].reshape(-1)

array([22.02787 , 15.325505, 17.008503, 30.425903, 14.221279],
      dtype=float32)

In [22]:
y_test[:5]

array([20.1, 11.9, 20.6, 33.2, 20.8])